### ISSUE TITLE
Support exponentiation of immutable matrices

### ISSUE THREAD

**Issue by olof3** [JuliaGeometry/ImmutableArrays.jl#44]
Hello

It would be useful with support for exponentiation of immutable matrices. With

A = Matrix2x2(eye(2))

A^n for n >= 0 do return the numerically correct matrix (there is a function ^(x, p::Integer) in intfuncs.jl) however for n=0 and n=1 it is just a normal array an not a Matrix2x2{Float64}, for n>1 the type of the returned matrix is of the (expected) type Matrix2x2{Float64}.

Looking at the implementation of  ^(x, p::Integer) it seems like a quick fix could be to add copy(::MatrixMxN{T}) and one(::MatrixMxN{T}) although it's perhaps not the cleanest one (the two functions could be added in their own right though).

(Expontentation of an immutable matrix with negative or non-integers throws errors, but those are less  used features I guess.)

**Comment by sjkelly** [comment]
`copy` should definitely be implemented as a no-op. 

The issue with `one` is really the call to `eye` in: https://github.com/JuliaLang/julia/blob/3b305b0e750d222d665efd8d49de38c0f64a1e1c/base/array.jl#L229-L233
I don't see a good way to do this in `Base`, so implementing a specific `one` seems like the easiest
option.

**Comment by sjkelly** [comment]
This should be fixed on master. Once CI give me a green I will tag a 0.0.9 for METADATA. Thanks for reporting this bug!

**Comment by olof3** [comment]
Thanks!
