### ISSUE TITLE
Deprecation?

### ISSUE THREAD

**Issue by sjkelly** [JuliaGeometry/ImmutableArrays.jl#46]
Since FixedSizeArrays seems to be reaching maturity, these packages are redundant. I think by 0.5, there should be one package in this space. These are the current packages depending on ImmutableArrays:

```
Contour      
GLAbstraction
Meshes       
GLWindow   
GLPlot
```

cc @SimonDanisch

**Comment by sjkelly** [comment]
Update: 
```
julia> Pkg.dependents("ImmutableArrays")
2-element Array{AbstractString,1}:
 "Qwt"   
 "GLPlot"
```

**Comment by SimonDanisch** [comment]
Jeez, I should really tag GLPlot.... the last tag was a hundred years ago... From what I remember, @tbreloff pretty much deprecated Qwt as well?

**Comment by tbreloff** [comment]
Yeah... I doubt there's a single person that has used Qwt in the last 6 months.

**Comment by SimonDanisch** [comment]
Plan, if someone trips over it, that person needs to port it to StaticArrays :P

**Comment by twadleigh** [comment]
I will archive this repo in the next 24 hours unless someone objects.
